#!/bin/bash
echo "#v19# To use this in cli use"
echo "sudo nano /bin/usr/prunes
# copy the next 3 lines into it with, and chmod it to 755  
#!/bin/bash
bash <(curl -s https://raw.githubusercontent.com/tek-aevl/umupdate/refs/heads/main/prunes))
echo 'bye';";
echo "#To use run"
echo "bash prunes"

echo "Starting!"
echo "setting functions"
#Function to check and copy SSH key to a remote host if needed
function copy_ssh_key() {
    if [[ ! -f ~/.ssh/id_rsa.pub ]]; then
        echo "SSH key not found. Generating a new SSH key..."
        ssh-keygen -t rsa
    fi
    # Check if the SSH key is already present on the remote host
   if ! ssh-add -L | grep -qF "$(cat ~/.ssh/id_rsa.pub)"; then
        #read -p "Enter the IP address or hostname of the remote host: " ip
       echo "Current client $ip"
        ssh-copy-id "$ip"
    else
        echo "SSH key is already copied to the remote host. No need to copy again."
    fi
}

# Function to check if Pi-hole is installed and running on a host
function check_pihole {
  # Check if the Pi-hole service is running
  if ssh -q -o ConnectTimeout=1 $1 "systemctl is-active pihole-FTL.service &> /dev/null"; then
    # Check if the Pi-hole web interface is accessible
    if curl -s -I -H "Host: pi.hole" http://$1/admin/ &> /dev/null; then
      return 0  # Pi-hole is installed and running
    fi
  fi
  return 1  # Pi-hole is not installed or not running
}
echo "...done..."

# Function to prompt the user for ARP inclusion
prompt_arp() {
    read -p "Do you want to include ARP in the IP list? (Y/N): " choice
    case "$choice" in
        [yY] | [yY][eE][sS])
            echo "Retrieving ARP table"
           if [ -f ~/arp_ip_list ]; then
                      cat ~/arp_ip_list
               read -p "~/arp_ip_list already exists. Do you want to overwrite it? (y/n): " overwrite
                  if [ "$overwrite" = "y" ]; then
                   arp_ip_list=$(arp -av | awk '{print $2}' | sed 's/[()]//g')
                   echo "$arp_ip_list" > ~/arp_ip_list
                   echo "$arp_ip_list has been overwritten."
                  else
                    arp_ip_list=$(<~/arp_ip_list)
                    echo "$arp_ip_list No changes made to $arp_ip_list ..."
                    sleep 1
                  fi
                else
                  arp_ip_list=$(<~/arp_ip_list)
              echo "$arp_ip_list has loaded."
          fi
          echo "$arp_ip_list ...done..."          
            sleep 2
            ;;
        [nN] | [nN][oO])
            arp_ip_list=""
            ;;
        *)
            echo "Invalid choice. Defaulting to no ARP."
            arp_ip_list=""
            ;;
    esac
}

prompt_arp

echo "Retrieving active clients over the bridge"
# Retrieve active clients in the bridge
bridge_clients=$(ip neigh show dev virbr0 | awk '{print $1}') && echo $bridge_clients
echo "$bridge_clients ...done..."

echo "Retrieve Tailscale client IP addresses"
# Retrieve Tailscale client IP addresses from 'tailscale status' command
##old# tailscale_ip_list=$(tailscale status | grep -oE '10\.[0-9]+\.[0-9]+\.[0-9]+')
tailscale_ip_list=$(sudo tailscale status | grep -Eo '100\.[0-9]+\.[0-9]+\.[0-9]+' | awk '!seen[$0]++')
echo "Tailscale Client List"
echo "$tailscale_ip_list"
echo ".!.done.!."

echo "Retrieving custom_ip_list"
# custom list put the next line in a new file called custom_ip_list
#custom_ip_list="0.0.0.0"$'\n'"0.0.0.0"
custom_ip_list=$(grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}' ~/custom_ip_list)
cat ~/custom_ip_list
echo "custom_list" && sleep 2
echo "$custom_ip_list  ...done..."

echo "Retrieving ignore_ip_list"
# ignore list file needed ignore_ip_list
#ignore_ip_list="0.0.0.0"$'\n'"0.0.0.0"
ignore_ip_list=$(grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}' ~/ignore_ip_list)
cat <<< "$ignore_ip_list" > ignore_list.txt
echo "ignore list created" && sleep 2

# Combine the IP lists based on user choice
if [ -n "$arp_ip_list" ]; then
  #withARP
    ip_list="$bridge_clients"$'\n'"$custom_ip_list"$'\n'"$arp_ip_list"$'\n'"$tailscale_ip_list"
else
  #noarp
    ip_list="$bridge_clients"$'\n'"$custom_ip_list"$'\n'"$tailscale_ip_list"
fi

echo "$ip_list ...ip list..."

echo "Removing IPs listed in the ignore list sorting then removing duplicates"
while IFS= read -r ip; do
    ip_list=$(echo "$ip_list" | grep -vFx "$ip")
done < ignore_list.txt

 ip_list=$(echo "$ip_list" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort -u)

 
# Step 4: Output the final combined list
echo "#####Final combined list:#####"
echo "$ip_list"

echo "Working this out"
# Iterate over each IP address and perform SSH connection

for ip in $ip_list; do
    # Perform SSH connection to the device
     echo "Connecting to $ip"
     # Call ssh-copy-id function
    copy_ssh_key
    if check_pihole $ip; then
      echo "Pi-hole detected on $ip skipping"
    else
      echo "Pruning $ip"
   ssh -ty $ip "bash <(curl -s https://raw.githubusercontent.com/tek-aevl/umupdate/refs/heads/main/prune)"
    fi
echo "moving on from $ip"
done
